spring:
  application:
    name: restaurants
  datasource:
    url: jdbc:mysql://localhost:3306/restaurants
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false
