spring:
  application:
    name: restaurants
  datasource:
    url: jdbc:mysql://localhost/restaurants
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
