spring:
  application:
    name: restaurants
  datasource:
    url: jdbc:mysql://localhost:3306/restaurants
    username: admin
    password: password
    #url: ${DB_URL}
    #username: ${DB_USERNAME}
    #password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
